// cmd/vm/main.go
package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath" // <<< Ensure this is imported

	// VM specific execution path
	"github.com/deniskipeles/pylearn/internal/lexer"
	"github.com/deniskipeles/pylearn/internal/parser"
	"github.com/deniskipeles/pylearn/internal/vm"

	// Shared object model and stdlib init side effects
	"github.com/deniskipeles/pylearn/internal/object"
	_ "github.com/deniskipeles/pylearn/internal/stdlib/pyhttp"
	_ "github.com/deniskipeles/pylearn/internal/stdlib/pyos"
	_ "github.com/deniskipeles/pylearn/internal/stdlib/httpserver"
	"github.com/deniskipeles/pylearn/internal/stdlib/pysys"
)

func main() {
	// --- Capture Command Line Arguments & Initialize Sys ---
	goArgs := os.Args
	pylearnArgv := make([]object.Object, len(goArgs))
	for i, arg := range goArgs { pylearnArgv[i] = &object.String{Value: arg} }
	argvList := &object.List{Elements: pylearnArgv}
	pysys.InitializeSysModule(argvList)

	// --- Argument Handling ---
	filename := ""
	if len(goArgs) >= 2 {
		filename = goArgs[1]
	} else {
		 fmt.Fprintf(os.Stderr, "Usage: %s <filename.py> [args...]\n", filepath.Base(goArgs[0]))
		 os.Exit(1)
	}

	// --- Determine Script Directory ---
	scriptDir := "." // Default to current directory if absolute path fails
	absPath, err := filepath.Abs(filename)
	if err == nil {
		// We have an absolute path, get the directory containing the file
		scriptDir = filepath.Dir(absPath)
	} else {
		// Couldn't get absolute path, try getting dir from original filename
		fmt.Fprintf(os.Stderr, "Warning: could not determine absolute path for '%s': %v. Using directory of relative path.\n", filename, err)
		scriptDir = filepath.Dir(filename)
        // If filename was just "script.py", Dir returns ".", which is usually desired fallback.
	}
    // Clean the path (removes redundant separators, etc.)
    scriptDir = filepath.Clean(scriptDir)
	// fmt.Printf("--- Determined Script Directory: %s ---\n", scriptDir)
    // --- END Determine Script Directory ---


	// --- File Reading ---
	sourceBytes, err := ioutil.ReadFile(filename) // Use original filename here
	if err != nil { fmt.Fprintf(os.Stderr, "Error reading file '%s': %v\n", filename, err); os.Exit(1) }
	source := string(sourceBytes)

	// --- Lexing & Parsing (Common to both) ---
	l := lexer.New(source)
	p := parser.New(l)
	program := p.ParseProgram()
	if len(p.Errors()) != 0 { printParserErrors(os.Stderr, p.Errors()); os.Exit(1) }

	// --- COMPILER AND VM EXECUTION ---

	// 1. Compile
	comp := vm.NewCompiler()
	errComp := comp.Compile(program)
	if errComp != nil {
		fmt.Fprintf(os.Stderr, "Compilation failed:\n%s\n", errComp)
		os.Exit(1)
	}
	fmt.Println("--- Compilation Finished ---") // DEBUG

	//  // 2. Get Bytecode and Print it for Debugging
	 bytecode := comp.Bytecode()
	//  fmt.Println("--- Generated Bytecode ---")
	//  fmt.Printf("Constants (%d):\n", len(bytecode.Constants))
	//  for i, cnst := range bytecode.Constants {
	// 	  fmt.Printf("  [%d]: %s\n", i, cnst.Inspect())
	//  }
	//  fmt.Println("Instructions:")
	//  fmt.Println(bytecode.Instructions.String())
	//  fmt.Println("--------------------------")

	 // 3. Set up VM
	 globals := make([]object.Object, vm.GlobalsSize)
	 // *** Use the constructor that accepts the script directory ***
	 machine := vm.NewWithGlobalsStoreAndDir(bytecode, globals, scriptDir) // <<< Use the correct constructor
	//  fmt.Printf("--- Initializing VM with Script Directory: %s ---\n", scriptDir) // Log initialization

	 // --- Populate VM's native modules ---
	 registeredModules := object.GetAllRegisteredModules()
	 machine.SetNativeModules(registeredModules) // Assumes SetNativeModules exists on *VM

	 // 4. Run VM
	 fmt.Println("--- Running VM ---")
	 errRun := machine.Run()
	 if errRun != nil {
        // Print the actual Pylearn error if possible
        if pyErr, ok := errRun.(object.Object); ok && object.IsError(pyErr){
            fmt.Fprintf(os.Stderr, "VM Runtime Error: %s\n", pyErr.Inspect())
        } else {
		    fmt.Fprintf(os.Stderr, "VM Execution Failed: %v\n", errRun)
        }
		os.Exit(1)
	 }

	 // 5. Get Result (Optional)
	 result := machine.LastPoppedStackElem()
	 fmt.Println("--- VM Finished ---")
	 // Only print final element if it's not NULL (cleaner output)
	 if result != nil && result.Type() != object.NULL_OBJ {
		  fmt.Println("Final Stack Elem:", result.Inspect())
	 }

	 os.Exit(0)
}

// printParserErrors helper function
func printParserErrors(out *os.File, errors []string) {
    fmt.Fprintln(out, "Parser errors encountered:")
    for _, msg := range errors {
        fmt.Fprintf(out, "\t%s\n", msg)
    }
}