//go:build sw

// pylearn/internal/constants/ast.go
//
package constants

// pylearn/internal/ast/ast.go
const (
	AstProgramTokenLiteralDefault         = ""
	AstExpressionStatementStringDefault   = ""
	AstLetStatementAssignOp               = " = "
	AstParameterDefaultAssignOp           = "="
	AstFunctionLiteralCallParens          = "("
	AstFunctionLiteralArgSeparator        = ", "
	AstFunctionLiteralBodyColon           = ":\n"
	AstFunctionLiteralBodyEllipsis        = ": ..."
	AstAwaitExpressionFormat              = "await (%s)"
	AstStarredArgumentPositionalPrefix    = "*"
	AstCallExpressionParens               = "("
	AstCallExpressionArgSeparator         = ", "
	AstCallExpressionCloseParens          = ")"
	AstListLiteralOpenBracket             = "["
	AstListLiteralSeparator               = ", "
	AstListLiteralCloseBracket            = "]"
	AstListComprehensionOpenBracket       = "["
	AstListComprehensionCloseBracket      = "]"
	AstDictLiteralOpenBrace               = "{"
	AstDictLiteralPairSeparator           = ": "
	AstDictLiteralSeparator               = ", "
	AstDictLiteralCloseBrace              = "}"
	AstIndexExpressionOpenParen           = "("
	AstIndexExpressionOpenBracket         = "["
	AstIndexExpressionCloseBracket        = "]"
	AstIndexExpressionCloseParen          = ")"
	AstSliceExpressionOpenParen           = "("
	AstSliceExpressionOpenBracket         = "["
	AstSliceExpressionColon               = ":"
	AstSliceExpressionCloseBracket        = "]"
	AstSliceExpressionCloseParen          = ")"
	AstWhileStatementColonNewline         = ":\n"
	AstForStatementColon                  = ":"
	AstWithStatementColonNewline          = ":\n"
	AstClassStatementSuperclassOpenParen  = "("
	AstClassStatementSuperclassSeparator  = ", "
	AstClassStatementSuperclassCloseParen = ")"
	AstClassStatementColonNewline         = ":\n"
	AstClassStatementBodyEllipsis         = " ..."
	AstDotExpressionOpenParen             = "("
	AstDotExpressionDotOperator           = "."
	AstDotExpressionCloseParen            = ")"
	AstImportStatementSpace               = " "
	AstFromImportStatementSpace           = " "
	AstFromImportStatementImportAll       = "*"
	AstFromImportStatementNameSeparator   = ", "
	AstExceptHandlerColonNewline          = ":\n"
	AstRaiseStatementSpace                = " "
	AstTupleLiteralOpenParen              = "("
	AstTupleLiteralSeparator              = ", "
	AstTupleLiteralTrailingComma          = ","
	AstTupleLiteralCloseParen             = ")"
	AstSetLiteralOpenBrace                = "{"
	AstSetLiteralSeparator                = ", "
	AstSetLiteralCloseBrace               = "}"
	AstSetComprehensionOpenBrace          = "{"
	AstSetComprehensionCloseBrace         = "}"

	AstGetTokenIllegalLiteral           = "internal" // Used in GetToken for fallback
	AstWithStatementEmptyBodyComment    = "  pass // (empty body)\n"
	AstKeywordArgumentAssignOp          = "="
	AstStarredArgumentKeywordPrefix     = "**"
	AstListComprehensionForKeyword      = " for "
	AstListComprehensionInKeyword       = " in "
	AstListComprehensionIfKeyword       = " if "
	AstWhileStatementWhileKeyword       = "while "
	AstForStatementInKeyword            = " in "
	AstWithStatementWithKeyword         = "with "
	AstWithStatementAsKeyword           = " as "
	AstClassStatementClassKeyword       = "class "
	AstPassStatementPassKeyword         = "pass"
	AstFromImportStatementImportKeyword = " import "
	AstImportNamePairAsKeyword          = " as "
	AstTryStatementTryKeyword           = "try:\n"
	AstExceptHandlerExceptKeyword       = "\nexcept"
	AstExceptHandlerAsKeyword           = " as "
	AstTryStatementFinallyKeyword       = "\nfinally:\n"
	AstSetComprehensionForKeyword       = " for "
	AstSetComprehensionInKeyword        = " in "
	AstSetComprehensionIfKeyword        = " if "
)
