//go:build en

// pylearn/internal/constants/builtins.go
package constants

// pylearn/internal/builtins/builtins_collections.go
const (
	BuiltinsCollectionsLenArgCountError           = "len() takes exactly one argument (%d given)"
	BuiltinsCollectionsLenAttrNotCallable         = "__len__ attribute of type %s is not callable"
	BuiltinsCollectionsLenShouldReturnInteger     = "__len__() should return an integer, not '%s'"
	BuiltinsCollectionsLenShouldReturnNonNegative = "__len__() should return >= 0"
	BuiltinsCollectionsObjectHasNoLen             = "object of type '%s' has no len()"
	BuiltinsCollectionsRangeArgTypeError          = "TypeError: '%s' object cannot be interpreted as an integer (argument %d for %s)"
	BuiltinsCollectionsRangeStepZeroError         = "range() arg 3 must not be zero"
	BuiltinsCollectionsRangeArgCountError         = "range expected at most 3 arguments, got %d"
	BuiltinsCommonDuplicateRegistration           = "Duplicate builtin registration: "
	BuiltinsRangeFuncName                         = "range"
	BuiltinsLenFuncName                           = "len"
)

// pylearn/internal/builtins/builtins_debug.go
const (
	BuiltinsDebugHelpArgCountError      = "Expected 0 or 1 arguments for help()"
	BuiltinsDebugHelpWelcomeMessage     = "Welcome to Pylearn help utility!"
	BuiltinsDebugHelpNotImplemented     = "Interactive help is not implemented. Pass an object to help()."
	BuiltinsDebugHelpOnObjectFormat     = "Help on %s object:\n"
	BuiltinsDebugHelpDocumentationTitle = "\nDocumentation:\n"
	BuiltinsDebugHelpAttributeError     = "Error retrieving attribute '__doc__': %s"
	BuiltinsGetattrFuncName             = "getattr"
	BuiltinsStrFuncName                 = "str"
	BuiltinsHelpFuncName                = "help"
)

// pylearn/internal/builtins/builtins_fstring.go
const (
	BuiltinsFstringFormatStringFnArgCountError    = "f() takes exactly 1 argument (the f-string literal), got %d"
	BuiltinsFstringFormatStringFnArgTypeError     = "f() argument must be a string, not %s"
	BuiltinsFstringUnterminatedExpression         = "f-string: unterminated expression (missing '}') starting at index %d"
	BuiltinsFstringEmptyExpressionNotAllowed      = "f-string: empty expression {} not allowed"
	BuiltinsFstringSyntaxErrorInExpression        = "SyntaxError in f-string expression '%s': %s"
	BuiltinsFstringExpressionParsedToNoStatements = "f-string: expression '%s' parsed to no statements"
	BuiltinsFstringContentMustBeExpression        = "f-string: content of {} ('%s') must be an expression"
	BuiltinsFstringStrBuiltinNotFound             = "'str' built-in not found for f-string formatting"
	BuiltinsFstringErrorConvertingResult          = "Error converting f-string expression result for '%s' to string: %s"
	BuiltinsFstringStrDidNotReturnString          = "Pylearn str() on f-string expression result did not return a string (got %s)"
	BuiltinsFstringSingleBraceNotAllowed          = "f-string: single '}' is not allowed outside of an expression"
	BuiltinsFormatStringFuncName                  = "format_str"
	BuiltinsFormatStrFuncName                     = "f"

	BuiltinFormatSpecifier_F_RequiresFloatOrIntegerNot_STRINGFORMATER = "format specifier 'f' requires a float or integer, not %s"
)

// pylearn/internal/builtins/builtins_io.go
const (
	BuiltinsIOStrBuiltinNotFound         = "'str' built-in not found"
	BuiltinsIOErrorDuringStr             = "<Error during str(): %s -> %s>"
	BuiltinsIONonStringFromStr           = "<Non-string result from str(): %s>"
	BuiltinsIOInputArgCountError         = "input expected at most 1 argument, got %d"
	BuiltinsIOInputArgConvertError       = "input() argument could not be converted to string: %s"
	BuiltinsIOInputStrNotReturned        = "str() did not return a string for input prompt"
	BuiltinsIOEOFReadingLine             = "EOF when reading a line"
	BuiltinsIOOpenArgCountError          = "open() takes 1 or 2 arguments (%d given)"
	BuiltinsIOOpenFileArgTypeError       = "open() argument 'file' must be str or bytes, not %s"
	BuiltinsIOOpenModeArgTypeError       = "open() argument 'mode' must be str, not %s"
	BuiltinsIOOpenTextAndBinaryModeError = "can't have text and binary mode at once"
	BuiltinsIOOpenInvalidMode            = "invalid mode: '%s'"
	BuiltinsIOOpenErrorFormat            = "[Errno %d] %s: '%s'"
	BuiltinsIOFileReadError              = "Error reading file '%s': %v\n"
	BuiltinsIOFileReadFailed             = "Error reading file '%s': %v"
	BuiltinsIOOpenReadMode               = "r"
	BuiltinsIOOpenWriteMode              = "w"
	BuiltinsIOOpenAppendMode             = "a"
	BuiltinsIOOpenExclusiveMode          = "x"
	BuiltinsIOBinaryModeChar             = "b"
	BuiltinsIOTextModeChar               = "t"
	BuiltinsIOOpenReadTextMode           = "rt"
	BuiltinsIOOpenReadBinaryMode         = "rb"
	BuiltinsIOOpenWriteTextMode          = "wt"
	BuiltinsIOOpenWriteBinaryMode        = "wb"
	BuiltinsIOOpenAppendTextMode         = "at"
	BuiltinsIOOpenAppendBinaryMode       = "ab"
	BuiltinsIOOpenReadPlusMode           = "r+"
	BuiltinsIOOpenReadBinaryPlusMode     = "rb+"
	BuiltinsIOOpenWritePlusMode          = "wt+"
	BuiltinsIOOpenWriteBinaryPlusMode    = "wb+"
	BuiltinsIOOpenAppendPlusMode         = "at+"
	BuiltinsPrintFuncName                = "print"
	BuiltinsInputFuncName                = "input"
	BuiltinsOpenFuncName                 = "open"
)

// pylearn/internal/builtins/builtins_iter.go
const (
	BuiltinsIterTokenLiteral            = "<iter>"
	BuiltinsIterArgCountError           = "iter() takes 1 or 2 arguments (%d given)"
	BuiltinsIterCallableBuiltinNotFound = "'callable' built-in not found"
	BuiltinsIterVMustBeCallable         = "iter(v, w): v must be callable"
	BuiltinsIterWarningErrorIgnored     = "Warning: Error ignored from callable in iter(): %s\n"
	BuiltinsNextTokenLiteral            = "<next>"
	BuiltinsNextArgCountError           = "next() takes 1 or 2 arguments (%d given)"
	BuiltinsNextObjectNotIterator       = "'%s' object is not an iterator"
	BuiltinsEnumerateArgCountError      = "enumerate() takes 1 or 2 arguments (%d given)"
	BuiltinsEnumerateStartArgTypeError  = "enumerate() 'start' argument must be an integer or None, not %s"
	BuiltinsZipNotImplemented           = "zip() built-in not implemented"
	BuiltinsMapNotImplemented           = "map() built-in not implemented"
	BuiltinsFilterNotImplemented        = "filter() built-in not implemented"
	BuiltinsReversedNotImplemented      = "reversed() built-in not implemented"
	BuiltinsAllArgCountError            = "all() takes exactly one argument (%d given)"
	BuiltinsAllIsTruthyPropagatedError  = "(from __bool__/__len__): %v"
	BuiltinsAnyArgCountError            = "any() takes exactly one argument (%d given)"
	BuiltinsAnyIsTruthyPropagatedError  = "(from __bool__/__len__): %v"
	BuiltinsCallableFuncName            = "callable"
	BuiltinsIterCallableSource          = "callable"
	BuiltinsIterFuncName                = "iter"
	BuiltinsNextFuncName                = "next"
	BuiltinsEnumerateFuncName           = "enumerate"
	BuiltinsZipFuncName                 = "zip"
	BuiltinsMapFuncName                 = "map"
	BuiltinsFilterFuncName              = "filter"
	BuiltinsReversedFuncName            = "reversed"
	BuiltinsAllFuncName                 = "all"
	BuiltinsAnyFuncName                 = "any"
)

// pylearn/internal/builtins/builtins_math.go
const (
	BuiltinsMathAbsArgCountError                 = "abs() takes exactly one argument (%d given)"
	BuiltinsMathBadOperandTypeAbs                = "bad operand type for abs(): %s"
	BuiltinsMathRoundArgCountError               = "round() takes 1 or 2 arguments (%d given)"
	BuiltinsMathRoundNdigitsTypeError            = "'ndigits' argument must be integer or None, not %s"
	BuiltinsMathRoundTypeNotDefineError          = "type %s doesn't define __round__ method"
	BuiltinsMathPowArgCountError                 = "pow() takes 2 or 3 arguments (%d given)"
	BuiltinsMathPow3rdArgTypeError               = "pow() 3rd argument must be None or an integer, not %s"
	BuiltinsMathPowUnsupportedOperandTypeModulo  = "unsupported operand type(s) for pow() with modulo: '%s', '%s'"
	BuiltinsMathPowExponentNegativeError         = "pow() exponent cannot be negative with modulo"
	BuiltinsMathPow3rdArgZeroError               = "pow() 3rd argument cannot be 0"
	BuiltinsMathPowIntResultTooLarge             = "integer pow() result with modulo too large"
	BuiltinsMathZeroRaisedNegativePower          = "0 cannot be raised to a negative power"
	BuiltinsMathIntPowerResultTooLarge           = "integer power result too large"
	BuiltinsMathPowUnsupportedOperandType        = "unsupported operand type(s) for ** or pow(): '%s' and '%s'"
	BuiltinsMathDivmodArgCountError              = "divmod() takes exactly two arguments (%d given)"
	BuiltinsMathIntegerDivOrModuloByZero         = "integer division or modulo by zero"
	BuiltinsMathDivmodUnsupportedOperandType     = "unsupported operand type(s) for divmod(): '%s' and '%s'"
	BuiltinsMathSumArgCountError                 = "sum() takes 1 or 2 arguments (%d given)"
	BuiltinsMathSumUnsupportedOperandAdd         = "unsupported operand type(s) for +: '%s' and '%s'"
	BuiltinsMathMinMaxArgCountError              = "%s expected 1 or more arguments, got 0"
	BuiltinsMathMinMaxEmptySequence              = "%s() arg is an empty sequence"
	BuiltinsMathMinMaxNotSupportedBetweenNumber  = "'%s' not supported between instances of 'number' and '%s'"
	BuiltinsMathMinMaxNotSupportedBetweenStr     = "'%s' not supported between instances of 'str' and '%s'"
	BuiltinsMathFormatBasedIntArgCountError      = "%s() takes exactly one argument (%d given)"
	BuiltinsMathObjectCannotBeInterpretedInteger = "'%s' object cannot be interpreted as an integer"
	BuiltinsMathHashArgCountError                = "hash() takes exactly one argument (%d given)"
	BuiltinsMathUnhashableType                   = "unhashable type: %s"
	BuiltinsMathFailedToHashObject               = "failed to hash object: %v"

	BuiltinsBinPrefix      = "0b"
	BuiltinsOctPrefix      = "0o"
	BuiltinsHexPrefix      = "0x"
	BuiltinsAbsFuncName    = "abs"
	BuiltinsRoundFuncName  = "round"
	BuiltinsPowFuncName    = "pow"
	BuiltinsDivmodFuncName = "divmod"
	BuiltinsSumFuncName    = "sum"
	BuiltinsMinFuncName    = "min"
	BuiltinsMaxFuncName    = "max"
	BuiltinsBinFuncName    = "bin"
	BuiltinsOctFuncName    = "oct"
	BuiltinsHexFuncName    = "hex"
	BuiltinsHashFuncName   = "hash"
)

// pylearn/internal/builtins/builtins_object.go
const (
	BuiltinsObjectIsInstanceArgCountError       = "isinstance() takes exactly 2 arguments (%d given)"
	BuiltinsObjectInstanceNilClassError         = "object.Instance has nil Class"
	BuiltinsObjectIsInstanceArg2TypeError       = "isinstance() arg 2 must be a type or tuple of types, not %s"
	BuiltinsObjectIsSubclassArgCountError       = "issubclass() takes exactly 2 arguments (%d given)"
	BuiltinsObjectIsSubclassArg1TypeError       = "issubclass() arg 1 must be a class"
	BuiltinsObjectIsSubclassArg2TypeError       = "issubclass() arg 2 must be a class or tuple of classes"
	BuiltinsObjectIdArgCountError               = "id() takes exactly one argument (%d given)"
	BuiltinsObjectHasattrArgCountError          = "hasattr() takes exactly two arguments (object, name)"
	BuiltinsObjectHasattrNameTypeError          = "hasattr(): attribute name must be string"
	BuiltinsObjectGetattrNameTypeError          = "getattr(): attribute name must be string"
	BuiltinsObjectGetattrArgCountError          = "getattr() takes two or three arguments (%d given)"
	BuiltinsObjectSetattrArgCountError          = "setattr() takes exactly three arguments (object, name, value)"
	BuiltinsObjectSetattrNameTypeError          = "setattr(): attribute name must be string"
	BuiltinsObjectSetattrAttributeError         = "'%s' object has no attribute '%s' (or cannot set attribute)"
	BuiltinsObjectDelattrArgCountError          = "delattr() takes exactly two arguments (object, name)"
	BuiltinsObjectDelattrNameTypeError          = "delattr(): attribute name must be string"
	BuiltinsObjectDelattrNotSupported           = "'%s' object attribute deletion not supported"
	BuiltinsObjectCallableArgCountError         = "callable() takes exactly one argument (%d given)"
	BuiltinsObjectDirNotImplemented             = "dir() built-in not implemented"
	BuiltinsObjectVarsNotImplemented            = "vars() built-in not implemented"
	BuiltinsObjectGlobalsNotImplemented         = "globals() built-in not implemented"
	BuiltinsObjectLocalsNotImplemented          = "locals() built-in not implemented"
	BuiltinsObjectPropertyNotImplemented        = "property() built-in not implemented"
	BuiltinsObjectSuperNoArgsNoContextError     = "super(): no arguments given and no context found"
	BuiltinsObjectSuperFirstArgTypeError        = "super(type, obj): first argument must be a class"
	BuiltinsObjectSuperArgCountError            = "super() takes 0 or 2 arguments (%d given)"
	BuiltinsObjectSuperInstanceHasNoClass       = "super(): instance argument has no class."
	BuiltinsObjectSuperSecondArgTypeError       = "super(type, obj): second argument must be an instance or a class, got %s"
	BuiltinsObjectStaticMethodArgCountError     = "staticmethod expected 1 argument, got %d"
	BuiltinsObjectStaticMethodArgTypeError      = "staticmethod argument must be a function, not %s"
	BuiltinsObjectClassMethodArgCountError      = "classmethod expected 1 argument, got %d"
	BuiltinsObjectClassMethodArgTypeError       = "classmethod argument must be a function, not %s"
	BuiltinsObjectHasNoAttribute                = "has no attribute"
	BuiltinsPropertyTakesAtMost4Arguments       = "property() takes at most 4 arguments"
	BuiltinsPropertyFgetArgumentMustBeACallable = "property() fget argument must be a callable"

	BuiltinsIsInstanceFuncName   = "isinstance"
	BuiltinsIsSubclassFuncName   = "issubclass"
	BuiltinsIdFuncName           = "id"
	BuiltinsHasAttrFuncName      = "hasattr"
	BuiltinsGetAttrFuncName      = "getattr"
	BuiltinsSetAttrFuncName      = "setattr"
	BuiltinsDelAttrFuncName      = "delattr"
	BuiltinsDirFuncName          = "dir"
	BuiltinsVarsFuncName         = "vars"
	BuiltinsGlobalsFuncName      = "globals"
	BuiltinsLocalsFuncName       = "locals"
	BuiltinsPropertyFuncName     = "property"
	BuiltinsSuperFuncName        = "super"
	BuiltinsStaticMethodFuncName = "staticmethod"
	BuiltinsClassMethodFuncName  = "classmethod"
	BuiltinsObjectFuncName       = "object"

	BuiltinsIntFuncName     = "int"
	BuiltinsFloatFuncName   = "float"
	BuiltinsBoolFuncName    = "bool"
	BuiltinsComplexFuncName = "complex"
	BuiltinsListFuncName    = "list"
	BuiltinsDictFuncName    = "dict"
	BuiltinsTupleFuncName   = "tuple"
	BuiltinsSetFuncName     = "set"
	BuiltinsBytesFuncName   = "bytes"
	BuiltinsFunctionType    = "function"
	BuiltinsObjectType      = "object"
	BuiltinsTypeType        = "type"
	BuiltinsFileType        = "file"
	BuiltinsModuleType      = "module"
)

// pylearn/internal/builtins/builtins_string.go
const (
	BuiltinsStringChrArgCountError          = "chr() takes exactly one argument (%d given)"
	BuiltinsStringChrIntInterpretationError = "'int' object cannot be interpreted as an integer for chr()"
	BuiltinsStringChrRangeError             = "chr() arg not in range(0x110000)"
	BuiltinsStringOrdArgCountError          = "ord() takes exactly one argument (%d given)"
	BuiltinsStringOrdCharLengthError        = "ord() expected a character (string of length 1), but string of length %d found"
	BuiltinsStringOrdByteStringLengthError  = "ord() expected a byte string of length 1, but got %d"
	BuiltinsStringOrdArgTypeError           = "ord() expected string or bytes of length 1, but %s found"
	BuiltinsStringFormatArgCountError       = "format() takes 1 or 2 arguments (%d given)"
	BuiltinsStringFormatArg2TypeError       = "format() argument 2 must be string, not %s"
	BuiltinsStringFormatUnknownIntCode      = "Unknown format code '%s' for object of type 'int'"
	BuiltinsStringFormatUnknownFloatCode    = "Unknown format code '%s' for object of type 'float'"
	BuiltinsStringFormatUnknownStrCode      = "Unknown format code '%s' for object of type 'str'"
	BuiltinsStringFormatNotImplemented      = "format() for type %s with spec '%s' not supported (needs __format__)"
	BuiltinsStringStrBuiltinNotFound        = "'str' built-in not found for format() fallback"
	BuiltinsStringStrFallbackError          = "str() fallback in format() did not return string (got %s)"
	BuiltinsStringFormatStrReturnError      = "__format__ must return a str, not %s"

	BuiltinsChrFuncName    = "chr"
	BuiltinsOrdFuncName    = "ord"
	BuiltinsFormatFuncName = "format"
)

// pylearn/internal/builtins/builtins_types.go
const (
	BuiltinsTypesTypeArgCountError                              = "type() takes exactly one argument (%d given)"
	BuiltinsTypesTypeNotImplementedError                        = "type() for classes not fully implemented"
	BuiltinsTypesIntBaseRangeError                              = "int() base must be >= 2 and <= 36, or 0"
	BuiltinsTypesIntNonStringBaseError                          = "int() can't convert non-string with explicit base"
	BuiltinsTypesIntInvalidLiteral                              = "invalid literal for int() with base %d: %s"
	BuiltinsTypesIntArgTypeError                                = "int() argument must be a string, a bytes-like object or a real number, not '%s'"
	BuiltinsTypesIntInvalidIntLiteral                           = "ValueError: invalid literal for int() with base %d: %q"
	BuiltinsTypesStrArgCountError                               = "str() takes exactly one argument (%d given)"
	BuiltinsTypesStrReprNonStringError                          = "__repr__ returned non-string (type %s)"
	BuiltinsTypesStrStrNonStringError                           = "__str__ returned non-string (type %s)"
	BuiltinsTypesStrBuiltinNotFound                             = "'str' built-in not found for format() fallback"
	BuiltinsTypesStrFallbackError                               = "str() fallback in format() did not return string (got %s)"
	BuiltinsTypesBoolArgCountError                              = "bool() takes at most 1 argument (%d given)"
	BuiltinsTypesBoolPropagatedFromIsTruthy                     = "(propagated from IsTruthy): %v"
	BuiltinsTypesListArgCountError                              = "list() takes at most 1 argument (%d given)"
	BuiltinsTypesDictArgCountError                              = "dict() with arguments not yet implemented"
	BuiltinsTypesReprArgCountError                              = "repr() takes exactly one argument (%d given)"
	BuiltinsTypesAsciiArgCountError                             = "ascii() takes exactly one argument (%d given)"
	BuiltinsTypesTupleArgCountError                             = "tuple() takes at most 1 argument (%d given)"
	BuiltinsTypesSetArgCountError                               = "set() takes at most 1 argument (%d given)"
	BuiltinsTypesSetUnhashableType                              = "unhashable type: '%s' in set() constructor"
	BuiltinsTypesSetHashFailed                                  = "failed to hash element for set() constructor: %v"
	BuiltinsTypesFrozensetNotImplemented                        = "frozenset() built-in not implemented"
	BuiltinsTypesBytesNotImplemented                            = "bytes() built-in not implemented"
	BuiltinsTypesByteArrayNotImplemented                        = "bytearray() built-in not implemented"
	BuiltinsTypesMemoryViewNotImplemented                       = "memoryview() built-in not implemented"
	BuiltinsTypesComplexNotImplemented                          = "complex() built-in not implemented"
	BuiltinsBytes_OR_BytearrayConstructorTakesAtMost3Arguments  = "bytes/bytearray constructor takes at most 3 arguments"
	BuiltinsIntegerArgumentMustBeSolitary                       = "integer argument must be solitary"
	BuiltinsNegativeCount                                       = "negative count"
	BuiltinsStringArgumentWithoutAnEncoding                     = "string argument without an encoding"
	BuiltinsObjectIsNotAnIterableOrCannotBeInterpretedAsBytes   = "object is not an iterable or cannot be interpreted as bytes"
	BuiltinsBytesLikeObjectRequiredNot_STRINGFORMATER           = "bytes-like object is required, not '%s'"
	BuiltinsBytesMustBeInRange_0_255                            = "bytes must be in range(0, 256)"
	BuiltinsFloatTakesAtMost1Argument_DIGITFORMATER_Given       = "float() takes at most 1 argument (%d given)"
	BuiltinsCouldNotConvertStringToFloat_STRINGFORMATER         = "could not convert string to float: %s"
	BuiltinsFloatArgumentMustBeStringOrNumberNot_STRINGFORMATER = "float() argument must be a string or a number, not '%s'"
	// "inf", "+inf", "infinity", "+infinity"
	BuiltinsInf            = "inf"
	Builtins_PLUS_Inf      = "+inf"
	BuiltinsInfinity       = "infinity"
	Builtins_PLUS_Infinity = "+infinity"
	// "-inf", "-infinity"
	Builtins_MINUS_Inf      = "-inf"
	Builtins_MINUS_Infinity = "-infinity"
	// "nan", "+nan", "-nan"
	BuiltinsNaN        = "nan"
	Builtins_PLUS_NaN  = "+nan"
	Builtins_MINUS_NaN = "-nan"

	BuiltinsNoneType                = "NoneType"
	BuiltinsBuiltinFunctionOrMethod = "builtin_function_or_method"
	BuiltinsTextIOWrapper           = "TextIOWrapper"
	BuiltinsIteratorType            = "iterator"
	BuiltinsStopIteration           = "StopIteration"
	BuiltinsMethodType              = "method"
	BuiltinsClassType               = "class"
	BuiltinsClassFormat             = "<class '%s'>"

	BinPrefixLower = "0b"
	BinPrefixUpper = "0B"
	OctPrefixLower = "0o"
	OctPrefixUpper = "0O"
	HexPrefixLower = "0x"
	HexPrefixUpper = "0X"

	BuiltinsTypeFuncName       = "type"
	BuiltinsReprFuncName       = "repr"
	BuiltinsAsciiFuncName      = "ascii"
	BuiltinsFrozensetFuncName  = "frozenset"
	BuiltinsByteArrayFuncName  = "bytearray"
	BuiltinsMemoryViewFuncName = "memoryview"
	// BuiltinsTupleFuncName      = "tuple"
	// BuiltinsSetFuncName        = "set"
	// BuiltinsBytesFuncName      = "bytes"
	// BuiltinsComplexFuncName    = "complex"
)
