//go:build sw
// pylearn/internal/constants/object.go
package constants

const (
	// Object Types (from object/object.go)
	OBJECT_TYPE_SUPER    = "SUPER"
	OBJECT_TYPE_CLASS    = "CLASS"
	OBJECT_TYPE_INSTANCE = "INSTANCE"

	// Super object (from object/class_object.go)
	SUPER_OBJECT_UNINITIALIZED_ERROR          = "super(): Pylearn super object is not properly initialized"
	SUPER_OBJECT_START_CLASS_NOT_IN_MRO_ERROR = "super(): 'StartClass' (%s) not in MRO of 'TargetType' (%s)"

	// Class object (from object/class_object.go)
	CLASS_OBJECT_INSPECT_FORMAT = "<class '%s'>"
	CLASS_OBJECT_NAME_ATTR      = "name"

	// Instance object (from object/class_object.go)
	INSTANCE_OBJECT_UNINITIALIZED_FORMAT = "<UninitializedInstance at %p>"
	INSTANCE_OBJECT_INSPECT_FORMAT       = "<%s object at %p>"
	INSTANCE_OBJECT_NO_CLASS_ERROR       = "Instance has no class associated"

	// MRO (from object/class_object.go)
	MRO_COMPUTE_NIL_CLASS_ERROR       = "cannot compute MRO for a nil class"
	MRO_COMPUTATION_FAILED_BASE_CLASS = "MRO computation failed for base class '%s' of '%s': %w"
	MRO_CONSISTENCY_ERROR             = "cannot create a consistent method resolution order (MRO) for class '%s'"
	OBJECT_CLASS_NAME                 = "object" // Name of the base object class

	// Environment (from object/environment.go)
	ENV_DELETE_NOT_FOUND = "name '%s' not found in this scope" // For error when deleting a non-existent item

	// Registry (from object/registry.go)
	REGISTRY_WARN_OVERWRITING_MODULE = "Warning: Overwriting native module registration for '%s'\n"
	REGISTRY_CRITICAL_NIL_MODULE     = "critical: native module '%s' found but is nil in registry"

	// Type objects (from object/type_objects.go)
	TYPE_CREATE_BUILTIN_ERROR = "critical: Base 'Exception' class not found for error: %s" // For creating exception classes if ObjectClass not init

)

// WebSocket object (from object/websocket_object.go)
const (
	WEBSOCKET_OBJ_TYPE                    = "WebSocket"
	WEBSOCKET_INSPECT_UNKNOWN_ADDR        = "unknown"
	WEBSOCKET_INSPECT_STATUS_OPEN         = "open"
	WEBSOCKET_INSPECT_STATUS_CLOSED       = "closed"
	WEBSOCKET_INSPECT_FORMAT              = "<WebSocket connection to %s (%s) at %p>"
	WEBSOCKET_RECEIVE_METHOD_NAME         = "receive"
	WEBSOCKET_RECEIVE_ARG_COUNT_ERROR     = "receive() takes no arguments (excluding self)"
	WEBSOCKET_ASYNC_RUNTIME_ERROR         = "WebSocket async runtime not available for receive()"
	WEBSOCKET_CLOSED_ERROR_MESSAGE        = "WebSocket is closed"
	WEBSOCKET_CLOSED_BY_PEER_ERROR        = "WebSocket closed by peer"
	WEBSOCKET_READ_ERROR_MESSAGE          = "WebSocket read error: %w"
	WEBSOCKET_RECEIVED_CLOSE_FRAME_REASON = "Received close frame from peer"
	WEBSOCKET_UNEXPECTED_DATA_TYPE_ERROR  = "WebSocket received unexpected data message type: %d"
	WEBSOCKET_SEND_METHOD_NAME            = "send"
	WEBSOCKET_SEND_ARG_COUNT_ERROR        = "send() takes 1 argument (data), got %d"
	WEBSOCKET_SEND_ON_CLOSED_ERROR        = "Cannot send on a closed WebSocket"
	WEBSOCKET_SEND_ARG_TYPE_ERROR         = "WebSocket send() argument must be String or Bytes, not %s"
	WEBSOCKET_WRITE_ERROR_MESSAGE         = "%v" // For WebSocketWriteError
	WEBSOCKET_CLOSE_METHOD_NAME           = "close"
	WEBSOCKET_CLOSE_ARG_COUNT_ERROR       = "close() takes at most 2 arguments (code, reason), got %d"
	WEBSOCKET_CLOSE_CODE_TYPE_ERROR       = "WebSocket close() code must be an integer"
	WEBSOCKET_CLOSE_REASON_TYPE_ERROR     = "WebSocket close() reason must be a string"
	WEBSOCKET_WARNING_CLOSE_WRITE_ERROR   = "Warning: WebSocket error writing close message: %v\n"
	WEBSOCKET_WARNING_FINAL_CLOSE_ERROR   = "Warning: WebSocket error on final close: %v\n"
	WEBSOCKET_METHOD_PREFIX               = "WebSocket." // Prefix for WebSocket method names

	WEBSOCKET_INSPECT_CLOSED          = "closed"
	WEBSOCKET_INSPECT_OPEN            = "open"
	WEBSOCKET_READ_ERROR              = "WebSocket read error: %w"
	WEBSOCKET_CLOSE_NORMAL_CLOSURE    = "WebSocket closed by peer"
	WEBSOCKET_RECEIVED_CLOSE_FRAME    = "Received close frame from peer"
	WEBSOCKET_UNEXPECTED_MESSAGE_TYPE = "WebSocket received unexpected data message type: %d"
	WEBSOCKET_SEND_TYPE_ERROR         = "WebSocket send() argument must be String or Bytes, not %s"
	WEBSOCKET_WRITE_ERROR             = "WebSocket write error: %v"
)

// Tuple object (from object/tuple_object.go)
const (
	TUPLE_INSPECT_FORMAT_SINGLE_ELEMENT = "(%s,)"
	TUPLE_INSPECT_FORMAT_MULTI_ELEMENT  = "(%s)"
	TUPLE_INSPECT_OPEN_PAREN            = "("
	TUPLE_INSPECT_SEPARATOR             = ", "
	TUPLE_INSPECT_TRAILING_COMMA        = ","
	TUPLE_INSPECT_CLOSE_PAREN           = ")"
	TUPLE_ITEM_INDEX_TYPE_ERROR         = "tuple indices must be integers, not %s"
	TUPLE_ITEM_INDEX_OUT_OF_RANGE       = "tuple index out of range"
	TUPLE_HASH_UNHASHABLE_ERROR         = "type error: unhashable type: '%s' in tuple"
	TUPLE_HASH_FAILED_ERROR             = "type error: failed to hash element in tuple: %w"
	TUPLE_COUNT_METHOD_NAME             = "count"
	TUPLE_COUNT_ARG_COUNT_ERROR         = "count() takes exactly one argument (%d given)"
	TUPLE_COUNT_ON_TUPLE_ERROR          = "descriptor 'count' requires a 'tuple' object but received a '%s'"
	TUPLE_INDEX_METHOD_NAME             = "index"
	TUPLE_INDEX_ARG_COUNT_ERROR         = "index() takes 1 to 3 arguments but %d were given"
	TUPLE_INDEX_ON_TUPLE_ERROR          = "descriptor 'index' requires a 'tuple' object but received a '%s'"
	TUPLE_INDEX_VALUE_NOT_IN_TUPLE      = "tuple.index(x): x not in tuple"
	TUPLE_INDEX_SLICE_INDICES_ERROR     = "slice indices must be integers or None for %s argument, not %s"
	TUPLE_LEN_ON_TUPLE_ERROR            = "__len__ must be called on a Tuple object"
	TUPLE_ADD_ARG_COUNT_ERROR           = "tuple.__add__ takes 1 argument (other)"
	TUPLE_ADD_ON_TUPLE_ERROR            = "__add__ must be called on a Tuple object"
	TUPLE_ADD_NOT_IMPLEMENTED_ERROR     = "NotImplemented" // When __radd__ or non-tuple is passed
	TUPLE_MUL_ARG_COUNT_ERROR           = "tuple.__mul__ takes 1 argument (count)"
	TUPLE_MUL_NOT_IMPLEMENTED_ERROR     = "NotImplemented" // When __rmul__ or non-int is passed
	TUPLE_MUL_OVERFLOW_ERROR            = "cannot fit 'int' into an index-sized integer"
	TUPLE_CONTAINS_ARG_COUNT_ERROR      = "__contains__() takes 1 argument (item)"
	TUPLE_CONTAINS_ON_TUPLE_ERROR       = "__contains__ must be called on a Tuple object"
	TUPLE_METHOD_PREFIX                 = "tuple." // Prefix for tuple method names
)

// String object (from object/string_object.go)
const (
	STRING_INSPECT_FORMAT                       = "%q"
	STRING_ITEM_INDEX_TYPE_ERROR                = "string indices must be integers, not %s"
	STRING_ITEM_INDEX_OUT_OF_RANGE              = "string index out of range"
	STRING_METHOD_PREFIX                        = "String."
	STRING_UPPER_METHOD_NAME                    = "upper"
	STRING_UPPER_ARG_COUNT_ERROR                = "upper() takes no arguments"
	STRING_LOWER_METHOD_NAME                    = "lower"
	STRING_LOWER_ARG_COUNT_ERROR                = "lower() takes no arguments"
	STRING_STARTSWITH_METHOD_NAME               = "startswith"
	STRING_STARTSWITH_ARG_COUNT_ERROR           = "startswith() takes 1 to 3 arguments but %d were given"
	STRING_STARTSWITH_PREFIX_TYPE_ERROR         = "startswithfirst arg must be str or a tuple of str (not implemented), not %s"
	STRING_SLICE_INDICES_TYPE_ERROR             = "slice indices must be integers or None, not %s"
	STRING_SPLIT_METHOD_NAME                    = "split"
	STRING_SPLIT_ARG_COUNT_ERROR                = "split() takes at most 2 arguments (%d given)"
	STRING_SPLIT_SEP_TYPE_ERROR                 = "split() separator must be str or None, not %s"
	STRING_SPLIT_MAXSPLIT_TYPE_ERROR            = "split() maxsplit must be int or None, not %s"
	STRING_JOIN_METHOD_NAME                     = "join"
	STRING_JOIN_ARG_COUNT_ERROR                 = "join() takes exactly one argument (%d given)"
	STRING_JOIN_ON_STRING_ERROR                 = "join() must be called on a String object (separator)"
	STRING_JOIN_ITERABLE_TYPE_ERROR             = "join() argument must be an iterable of strings (List/Tuple supported for now), not %s"
	STRING_SEQUENCE_ITEM_STR_ERROR              = "sequence item %d: expected str instance, %s found"
	STRING_STRIP_METHOD_NAME                    = "strip"
	STRING_LSTRIP_METHOD_NAME                   = "lstrip"
	STRING_RSTRIP_METHOD_NAME                   = "rstrip"
	STRING_STRIP_ON_STRING_ERROR                = "%s() must be called on a String object"
	STRING_STRIP_ARG_COUNT_ERROR                = "%s() takes at most 1 argument (%d given)"
	STRING_STRIP_CHARS_TYPE_ERROR               = "%s() argument must be str or None, not %s"
	STRING_STRIP_UNKNOWN_TYPE_ERROR             = "unknown strip type %s"
	STRING_ENDSWITH_METHOD_NAME                 = "endswith"
	STRING_ENDSWITH_ARG_COUNT_ERROR             = "endswith() takes 1 to 3 arguments but %d were given"
	STRING_ENDSWITH_SUFFIX_TYPE_ERROR           = "endswithfirst arg must be str or a tuple of str (not implemented), not %s"
	STRING_REPLACE_METHOD_NAME                  = "replace"
	STRING_REPLACE_ARG_COUNT_ERROR              = "replace() takes 2 or 3 arguments but %d were given"
	STRING_REPLACE_OLD_TYPE_ERROR               = "replace() argument 1 (old) must be str, not %s"
	STRING_REPLACE_NEW_TYPE_ERROR               = "replace() argument 2 (new) must be str, not %s"
	STRING_REPLACE_COUNT_TYPE_ERROR             = "replace() argument 3 (count) must be int or None, not %s"
	STRING_FIND_METHOD_NAME                     = "find"
	STRING_FIND_ARG_COUNT_ERROR                 = "find() takes 1 to 3 arguments but %d were given"
	STRING_FIND_SUB_TYPE_ERROR                  = "find() argument 1 (sub) must be str, not %s"
	STRING_ENCODE_METHOD_NAME                   = "encode"
	STRING_ENCODE_ARG_COUNT_ERROR               = "encode() takes 1 argument but %d were given"
	STRING_ENCODE_ON_STRING_ERROR               = "encode() must be called on a String object"
	STRING_DECODE_METHOD_NAME                   = "decode"
	STRING_DECODE_ARG_COUNT_ERROR               = "decode() takes 1 argument but %d were given"
	STRING_DECODE_ON_STRING_ERROR               = "decode() must be called on a String object"
	STRING_LEN_ON_STRING_ERROR                  = "__len__() must be called on a String object"
	STRING_CONTAINS_ON_STRING_ERROR             = "__contains__() must be called on a String object"
	STRING_FORMAT_METHOD_NAME                   = "format"
	STRING_FORMAT_ARG_COUNT_ERROR               = "format() called without self argument"
	STRING_FORMAT_ON_STRING_ERROR               = "format() must be called on a String object"
	STRING_FORMAT_SINGLE_BRACE_ERROR            = "Single '{' encountered in format string"
	STRING_FORMAT_INDEX_OUT_OF_RANGE            = "Replacement index %d out of range for positional args tuple"
	STRING_FORMAT_UNSUPPORTED_PLACEHOLDER_ERROR = "unsupported format string placeholder: {%s} (only {} and {index} supported)"
	STRING_FORMAT_SINGLE_CLOSING_BRACE_ERROR    = "Single '}' encountered in format string"
	STRING_FORMAT_NIL_ARG_ERROR                 = "<nil_arg_error>"
	STRING_FORMAT_NONE_KEYWORD                  = "None"
	STRING_SPLIT_ON_STRING_ERROR                = "split() must be called on a String object"
	STRING_STARTSWITH_ON_STRING_ERROR           = "startswith() must be called on a String object"
	STRING_ENDSWITH_ON_STRING_ERROR             = "endswith() must be called on a String object"
	STRING_REPLACE_ON_STRING_ERROR              = "replace() must be called on a String object"
	STRING_FIND_ON_STRING_ERROR                 = "find() must be called on a String object"
	STRING_CONTAINS_REQUIRES_STRING             = "'in <string>' requires string as left operand, not %s"

	STRING_STARTSWITH_SLICE_INDEX_ERROR    = "slice indices must be integers or None, not %s"
	STRING_ENDSWITH_SLICE_INDEX_ERROR      = "slice indices must be integers or None, not %s"
	STRING_FIND_SLICE_INDEX_ERROR          = "slice indices must be integers or None, not %s"
	STRING_FORMAT_UNSUPPORTED_PLACEHOLDER  = "unsupported format string placeholder: {%s} (only {} and {index} supported)"
	STRING_FORMAT_SINGLE_BRACE_NOT_ALLOWED = "Single '}' encountered in format string"
)

// Static/Class Method (from object/static_or_class_method_object.go)
const (
	STATIC_METHOD_OBJ_TYPE       = "STATIC_METHOD"
	CLASS_METHOD_OBJ_TYPE        = "CLASS_METHOD"
	STATIC_METHOD_ANON_NAME      = "<anonymous_static_method>"
	CLASS_METHOD_ANON_NAME       = "<anonymous_class_method>"
	STATIC_METHOD_INSPECT_FORMAT = "<staticmethod object wrapping %s at %p>"
	CLASS_METHOD_INSPECT_FORMAT  = "<classmethod object wrapping %s at %p>"
)

// SQLite (from object/sqlite_object.go)
const (
	SQLITE_CONNECTION_OBJ_TYPE            = "SQLITE_CONNECTION"
	SQLITE_CURSOR_OBJ_TYPE                = "SQLITE_CURSOR"
	SQLITE_CONN_INSPECT_FORMAT            = "<sqlite.Connection object at %p (path: %s, status: %s)>"
	SQLITE_CONN_STATUS_OPEN               = "open"
	SQLITE_CONN_STATUS_CLOSED             = "closed"
	SQLITE_CURSOR_INSPECT_FORMAT          = "<sqlite.Cursor object at %p (status: %s)>"
	SQLITE_CURSOR_STATUS_ACTIVE           = "active"
	SQLITE_CURSOR_STATUS_CLOSED           = "closed"
	SQLITE_CLOSED_CONN_ERROR              = "Cannot create cursor from closed connection"
	SQLITE_COMMIT_METHOD_NAME             = "commit"
	SQLITE_CLOSED_CURSOR_ERROR            = "Cannot execute on a closed cursor"
	SQLITE_EXECUTE_ARG_COUNT_ERROR        = "execute() takes 1 or 2 arguments (sql, parameters=None)"
	SQLITE_EXECUTE_SQL_TYPE_ERROR         = "execute() sql argument must be a string"
	SQLITE_EXECUTE_PARAMS_TYPE_ERROR      = "execute() parameters must be a tuple"
	SQLITE_EXECUTE_UNSUPPORTED_PARAM_TYPE = "Unsupported parameter type for SQL query: %s"
	SQLITE_SELECT_KEYWORD_LOWER           = "select"
	SQLITE_SELECT_KEYWORD_UPPER           = "SELECT"
	SQLITE_EXECUTE_QUERY_ERROR            = "Failed to execute query: %v"
	SQLITE_EXECUTE_STATEMENT_ERROR        = "Failed to execute statement: %v"
	SQLITE_FETCHONE_NO_QUERY_ERROR        = "Cannot fetchone() without executing a SELECT query first"
	SQLITE_FETCHONE_ROW_ITER_ERROR        = "Error during row iteration: %v"
	SQLITE_FETCHONE_SCAN_ROW_ERROR        = "Failed to scan row: %v"
	SQLITE_FETCHALL_NO_QUERY_ERROR        = "Cannot fetchall() without executing a SELECT query first"
	SQLITE_FETCHALL_ROW_ITER_ERROR        = "Error during row iteration: %v"
	SQLITE_FETCHALL_SCAN_ROW_ERROR        = "Failed to scan row: %v"
	SQLITE_CLOSE_CONN_ERROR               = "Error closing database connection: %v"
	SQLITE_UNSUPPORTED_DB_TYPE            = "unsupported database type: %T"
	SQLITE_CURSOR_METHOD_NAME             = "cursor"
	SQLITE_CLOSE_METHOD_NAME              = "close"
	SQLITE_EXECUTE_METHOD_NAME            = "execute"
	SQLITE_FETCHONE_METHOD_NAME           = "fetchone"
	SQLITE_FETCHALL_METHOD_NAME           = "fetchall"
	SQLITE_LASTROWID_ATTR_NAME            = "lastrowid"
	SQLITE_ROWCOUNT_ATTR_NAME             = "rowcount"
	SQLITE_TIME_FORMAT                    = "2006-01-02T15:04:05Z07:00" // RFC3339 for time.Time
)

// Set object (from object/set_object.go)
const (
	SET_EMPTY_INSPECT_FORMAT             = "set()"
	SET_INSPECT_OPEN_BRACE               = "{"
	SET_INSPECT_SEPARATOR                = ", "
	SET_INSPECT_CLOSE_BRACE              = "}"
	SET_ADD_METHOD_NAME                  = "add"
	SET_ADD_ARG_COUNT_ERROR              = "add() takes exactly one argument (%d given)"
	SET_ADD_ON_SET_ERROR                 = "descriptor 'add' requires a 'set' object but received a '%s'"
	SET_UNHASHABLE_TYPE_ERROR_FORMAT     = "unhashable type: '%s'" // General unhashable message for sets
	SET_FAILED_TO_HASH_ERROR_FORMAT      = "failed to hash element for set: %v"
	SET_REMOVE_METHOD_NAME               = "remove"
	SET_REMOVE_ARG_COUNT_ERROR           = "remove() takes exactly one argument (%d given)"
	SET_REMOVE_ON_SET_ERROR              = "descriptor 'remove' requires a 'set' object"
	SET_REMOVE_KEY_ERROR_FORMAT          = "%s" // For KeyError message with Inspect()
	SET_DISCARD_METHOD_NAME              = "discard"
	SET_DISCARD_ARG_COUNT_ERROR          = "discard() takes exactly one argument (%d given)"
	SET_DISCARD_ON_SET_ERROR             = "descriptor 'discard' requires a 'set' object"
	SET_POP_METHOD_NAME                  = "pop"
	SET_POP_ARG_COUNT_ERROR              = "pop() takes no arguments (%d given)"
	SET_POP_ON_SET_ERROR                 = "descriptor 'pop' requires a 'set' object"
	SET_POP_EMPTY_SET_ERROR              = "'pop from an empty set'"
	SET_CLEAR_METHOD_NAME                = "clear"
	SET_CLEAR_ARG_COUNT_ERROR            = "clear() takes no arguments (%d given)"
	SET_CLEAR_ON_SET_ERROR               = "descriptor 'clear' requires a 'set' object"
	SET_LEN_ON_SET_ERROR                 = "__len__() must be called on a Set object"
	SET_CONTAINS_ON_SET_ERROR            = "__contains__() must be called on a Set object"
	SET_BINARY_OP_ARG_COUNT_ERROR        = "%s() takes 1 argument (%d given)"
	SET_BINARY_OP_ON_SET_ERROR           = "descriptor '%s' requires a 'set' object"
	SET_UNION_METHOD_NAME                = "union"
	SET_INTERSECTION_METHOD_NAME         = "intersection"
	SET_DIFFERENCE_METHOD_NAME           = "difference"
	SET_SYMMETRIC_DIFFERENCE_METHOD_NAME = "symmetric_difference"
	SET_ISSUBSET_METHOD_NAME             = "issubset"
	SET_ISSUBSET_ON_SET_ERROR            = "descriptor 'issubset' requires a 'set' object"
	SET_ISSUPERSET_METHOD_NAME           = "issuperset"
	SET_ISSUPERSET_ON_SET_ERROR          = "descriptor 'issuperset' requires a 'set' object"
	SET_LT_METHOD_NAME                   = "__lt__"
	SET_GT_METHOD_NAME                   = "__gt__"
	SET_EQ_METHOD_NAME                   = "__eq__"
	SET_NE_METHOD_NAME                   = "__ne__"
	SET_EQ_ARG_COUNT_ERROR               = "__eq__ takes 1 argument"
	SET_NE_ARG_COUNT_ERROR               = "__ne__ takes 1 argument"
	SET_LT_ARG_COUNT_ERROR               = "__lt__ takes 1 argument"
	SET_GT_ARG_COUNT_ERROR               = "__gt__ takes 1 argument"
	SET_METHOD_PREFIX                    = "set." // Prefix for set method names

	SET_REMOVE_KEY_ERROR               = "%s" // For KeyError message with Inspect()
	SET_UNION_FUNC_NAME                = "union"
	SET_INTERSECTION_FUNC_NAME         = "intersection"
	SET_DIFFERENCE_FUNC_NAME           = "difference"
	SET_SYMMETRIC_DIFFERENCE_FUNC_NAME = "symmetric_difference"
	SET_ISSUBSET_FUNC_NAME             = "issubset"
	SET_ISSUPERSET_FUNC_NAME           = "issuperset"
)

// List object (from object/list_object.go)
const (
	LIST_INSPECT_FORMAT           = "[%s]"
	LIST_INDEX_TYPE_ERROR         = "list indices must be integers, not %s"
	LIST_INDEX_OUT_OF_RANGE       = "list index out of range"
	LIST_ADD_ARG_COUNT_ERROR      = "list.__add__ takes 1 argument (other)"
	LIST_CONTAINS_ARG_COUNT_ERROR = "__contains__() takes 1 argument (item)"
	LIST_SEQUENCE_ITEM_STR_ERROR  = "sequence item %d: expected str instance, %s found"

	LIST_INSPECT_OPEN_BRACKET          = "["
	LIST_INSPECT_SEPARATOR             = ", "
	LIST_INSPECT_CLOSE_BRACKET         = "]"
	LIST_ITEM_INDEX_TYPE_ERROR         = "list indices must be integers, not %s"
	LIST_ITEM_INDEX_OUT_OF_RANGE       = "list index out of range"
	LIST_ASSIGNMENT_INDEX_OUT_OF_RANGE = "list assignment index out of range"
	LIST_APPEND_METHOD_NAME            = "append"
	LIST_APPEND_ARG_COUNT_ERROR        = "append() takes exactly one argument (%d given)"
	LIST_APPEND_ON_LIST_ERROR          = "append() must be called on a List object"
	LIST_EXTEND_METHOD_NAME            = "extend"
	LIST_EXTEND_ARG_COUNT_ERROR        = "extend() takes exactly one argument (%d given)"
	LIST_EXTEND_ON_LIST_ERROR          = "extend() must be called on a List object"
	LIST_INSERT_METHOD_NAME            = "insert"
	LIST_INSERT_ARG_COUNT_ERROR        = "insert() takes exactly 2 arguments (%d given)"
	LIST_INSERT_ON_LIST_ERROR          = "insert() must be called on a List object"
	LIST_INSERT_INDEX_TYPE_ERROR       = "insert() index must be an integer, not %s"
	LIST_POP_METHOD_NAME               = "pop"
	LIST_POP_ARG_COUNT_ERROR           = "pop() takes at most 1 argument (%d given)"
	LIST_POP_EMPTY_LIST_ERROR          = "pop from empty list"
	LIST_POP_INDEX_OUT_OF_RANGE        = "pop index out of range"
	LIST_POP_INDEX_TYPE_ERROR          = "pop() index must be an integer or None, not %s"
	LIST_REMOVE_METHOD_NAME            = "remove"
	LIST_REMOVE_ARG_COUNT_ERROR        = "remove() takes exactly one argument (%d given)"
	LIST_REMOVE_ON_LIST_ERROR          = "remove() must be called on a List object"
	LIST_REMOVE_VALUE_NOT_IN_LIST      = "list.remove(x): x not in list"
	LIST_INDEX_METHOD_NAME             = "index"
	LIST_INDEX_ARG_COUNT_ERROR         = "index() takes 1 to 3 arguments (%d given)"
	LIST_INDEX_ON_LIST_ERROR           = "index() must be called on a List object"
	LIST_INDEX_SLICE_INDICES_ERROR     = "slice indices must be integers or None for start argument" // This is specifically for list.index's start/end args
	LIST_INDEX_VALUE_NOT_IN_LIST       = "%s is not in list"
	LIST_COUNT_METHOD_NAME             = "count"
	LIST_COUNT_ARG_COUNT_ERROR         = "count() takes exactly one argument (%d given)"
	LIST_COUNT_ON_LIST_ERROR           = "count() must be called on a List object"
	LIST_LEN_ON_LIST_ERROR             = "__len__() must be called on a List object"
	LIST_ADD_ON_LIST_ERROR             = "__add__ must be called on a List object"
	LIST_ADD_CONCAT_ERROR              = "can only concatenate list (not \"%s\") to list"
	LIST_CONTAINS_ON_LIST_ERROR        = "__contains__() must be called on a List object"
	LIST_METHOD_PREFIX                 = "List." // Prefix for list method names
	LIST_POP_ON_LIST_ERROR             = "pop() must be called on a List object"
)

// Object (from object/object.go)
const (
	OBJECT_TYPE_INTEGER            = "INTEGER"
	OBJECT_TYPE_FLOAT              = "FLOAT"
	OBJECT_TYPE_BOOLEAN            = "BOOLEAN"
	OBJECT_TYPE_STRING             = "STRING"
	OBJECT_TYPE_LIST               = "LIST"
	OBJECT_TYPE_DICT               = "DICT"
	OBJECT_TYPE_NULL               = "NULL"
	OBJECT_TYPE_RETURN_VALUE       = "RETURN_VALUE"
	OBJECT_TYPE_ERROR              = "ERROR"
	OBJECT_TYPE_FUNCTION           = "FUNCTION"
	OBJECT_TYPE_ASYNC_RESULT       = "ASYNC_RESULT"
	OBJECT_TYPE_BUILTIN            = "BUILTIN"
	OBJECT_TYPE_BREAK              = "BREAK"
	OBJECT_TYPE_CONTINUE           = "CONTINUE"
	OBJECT_TYPE_RANGE              = "RANGE"
	OBJECT_TYPE_BOUND_METHOD       = "BOUND_METHOD"
	OBJECT_TYPE_MODULE             = "MODULE"
	OBJECT_TYPE_TUPLE              = "TUPLE"
	OBJECT_TYPE_SET                = "SET"
	OBJECT_TYPE_BYTES              = "BYTES"
	OBJECT_TYPE_FILE               = "FILE"
	OBJECT_TYPE_ITERATOR           = "ITERATOR"
	OBJECT_TYPE_STOP_ITERATION_ERR = "STOP_ITERATION"
	OBJECT_TYPE_HTTP_RESPONSE      = "HTTP_RESPONSE"
	OBJECT_TYPE_HTTP_REQUEST       = "HTTP_REQUEST"

	OBJECT_BOUND_GO_METHOD_INSPECT_FORMAT           = "<bound native method %s>"
	OBJECT_HASHABLE_UNHASHABLE_ERROR                = "unhashable type: %s"
	OBJECT_INTEGER_INSPECT_FORMAT                   = "%d"
	OBJECT_FLOAT_INSPECT_FORMAT                     = "%g"
	OBJECT_BOOLEAN_INSPECT_FORMAT                   = "%t"
	OBJECT_BYTES_INSPECT_PREFIX                     = "b'"
	OBJECT_BYTES_INSPECT_SUFFIX                     = "'"
	OBJECT_BYTES_INSPECT_HEX_FORMAT                 = "\\x%02x"
	OBJECT_BYTES_INSPECT_SINGLE_QUOTE               = "\\'"
	OBJECT_BYTES_INSPECT_BACKSLASH                  = "\\\\"
	OBJECT_BYTES_INSPECT_TAB                        = "\\t"
	OBJECT_BYTES_INSPECT_NEWLINE                    = "\\n"
	OBJECT_BYTES_INSPECT_CARRIAGE_RETURN            = "\\r"
	OBJECT_BYTES_INDEX_TYPE_ERROR                   = "bytes indices must be integers, not %s"
	OBJECT_BYTES_INDEX_OUT_OF_RANGE                 = "bytes index out of range"
	OBJECT_NULL_INSPECT                             = "None"
	OBJECT_STOP_ITERATION_INSPECT_FORMAT            = "%s: %s"
	OBJECT_STOP_ITERATION_DEFAULT_MESSAGE           = "StopIteration"
	OBJECT_GENERIC_ITERATOR_INSPECT_FORMAT          = "<%s_iterator object at %p>"
	OBJECT_ERROR_INSPECT_FORMAT                     = "%s: %s"
	OBJECT_BREAK_INSPECT                            = "break"
	OBJECT_CONTINUE_INSPECT                         = "continue"
	OBJECT_RANGE_INSPECT_TWO_ARGS                   = "range(%d, %d)"
	OBJECT_RANGE_INSPECT_THREE_ARGS                 = "range(%d, %d, %d)"
	OBJECT_BOUND_METHOD_INSPECT_UNKNOWN_OWNER       = "<unknown owner>"
	OBJECT_BOUND_METHOD_INSPECT_CLASS_FORMAT        = "class %s"
	OBJECT_BOUND_METHOD_INSPECT_METHOD_NAME_DEFAULT = "<method>"
	OBJECT_BOUND_METHOD_INSPECT_FORMAT              = "<bound method %s.%s of %s>"
	OBJECT_MODULE_INSPECT_FORMAT                    = "<module '%s' from '%s'>"
	OBJECT_NOT_IMPLEMENTED_INSPECT                  = "NotImplemented"
	OBJECT_NOT_IMPLEMENTED_TYPE                     = "NOT_IMPLEMENTED_TYPE"
	OBJECT_BOUND_METHOD_INSPECT_CLASS_PLACEHOLDER   = "<OwnerClass>"

	OBJECT_ASYNC_RESULT_PENDING        = "pending"
	OBJECT_ASYNC_RESULT_FAILED_FORMAT  = "failed: %v"
	OBJECT_ASYNC_RESULT_COMPLETED      = "completed"
	OBJECT_ASYNC_RESULT_INSPECT_FORMAT = "<AsyncResult %s>"
)

// Iterator object (from object/iterators.go)
const (
	ITERATOR_ITER_METHOD_RETURN_ERROR   = "__iter__ returned non-iterator object of type '%s'"
	ITERATOR_SOURCE_LIST                = "list"
	ITERATOR_SOURCE_TUPLE               = "tuple"
	ITERATOR_SOURCE_STRING              = "string"
	ITERATOR_SOURCE_RANGE               = "range"
	ITERATOR_SOURCE_DICT_KEYS           = "dict_keys"
	ITERATOR_SOURCE_BYTES               = "bytes"
	ITERATOR_SOURCE_SET                 = "set"
	ITERATOR_GET_OBJECT_ITER_ERROR      = "'%s' object is not iterable"
	ITERATOR_DICT_KEY_DISAPPEARED_ERROR = "key disappeared during dict iteration"
	ITERATOR_SET_OP_ITERABLE_TYPE_ERROR = "'%s' object is not iterable for set operation '%s'"
	ITERATOR_SET_OP_UNHASHABLE_TYPE     = "unhashable type '%s' in iterable for set operation '%s'"
	ITERATOR_SET_OP_FAILED_TO_HASH      = "failed to hash element from iterable for set operation '%s': %v"
)

// HTTP Server object (from object/http_server_object.go)
const (
	SERVER_RESPONSE_OBJ_TYPE       = "ServerResponse"
	SERVER_RESPONSE_DEFAULT_STATUS = "200"
	SERVER_RESPONSE_INSPECT_FORMAT = "<ServerResponse [%s]>"
)

// HTTP object (from object/http_object.go)
const (
	HTTP_RESPONSE_INSPECT_FORMAT                     = "<HTTPResponse [%s] for %s>"
	HTTP_REQUEST_INSPECT_FORMAT                      = "<HTTPRequest [%s %s]>"
	HTTP_INTERNAL_NIL_RESPONSE                       = "Go HTTP response is nil"
	HTTP_REQUEST_BODY_READ_ERROR                     = "RequestError: Failed to read response body from '%s': %v"
	HTTP_REQUEST_HEADER_KEY_VALUE_ERROR              = "header keys and values must be strings (key: %s, val: %s)"
	HTTP_JSON_DECODE_EMPTY_CONTENT                   = "Empty response content cannot be decoded as JSON"
	HTTP_JSON_DECODE_ERROR_FORMAT                    = "%s (from content: %q)"
	HTTP_JSON_CONVERSION_ERROR                       = "Error converting decoded JSON to Pylearn objects: %v"
	HTTP_JSON_UNSUPPORTED_TYPE                       = "unsupported type %T in JSON conversion"
	HTTP_REQUEST_HEADERS_TYPE_ERROR                  = "headers argument must be a Dict or None, not %s"
	HTTP_REQUEST_PARAMS_TYPE_ERROR                   = "params argument must be a Dict or None, not %s"
	HTTP_REQUEST_PARAMS_CONVERSION_ERROR             = "error converting params: %v"
	HTTP_REQUEST_PARAMS_KEY_ERROR                    = "param keys must be strings, got %s"
	HTTP_REQUEST_CREATE_ERROR                        = "failed to create request: %v"
	HTTP_REQUEST_TIMEOUT_ERROR                       = "TimeoutError: request to %s timed out"
	HTTP_REQUEST_EXECUTION_ERROR                     = "failed to execute request to '%s': %v"
	HTTP_REQUEST_TYPE_ERROR_METHOD                   = "request() method argument must be a string, not %s"
	HTTP_REQUEST_TYPE_ERROR_URL                      = "request() url argument must be a string, not %s"
	HTTP_REQUEST_OPTIONS_TYPE_ERROR                  = "request() third argument, if provided, must be a Dict of options, not %s"
	HTTP_REQUEST_DATA_JSON_CONFLICT                  = "cannot specify both 'data' and 'json' arguments"
	HTTP_REQUEST_JSON_CONVERSION_ERROR               = "error converting json payload: %v"
	HTTP_REQUEST_JSON_MARSHAL_ERROR                  = "failed to marshal json payload: %v"
	HTTP_REQUEST_DATA_TYPE_ERROR                     = "'data' argument must be String, Bytes, or Dict, not %s"
	HTTP_REQUEST_TIMEOUT_VALUE_ERROR                 = "timeout must be an int or float, not %s"
	HTTP_REQUEST_TIMEOUT_POSITIVE_ERROR              = "timeout must be a positive number"
	HTTP_REQUEST_CONVERSION_ERROR                    = "error converting json payload: %v"
	HTTP_REQUEST_UNSUPPORTED_TYPE_JSON               = "type %s not serializable to JSON for request payload"
	HTTP_RESPONSE_JSON_METHOD_NAME                   = "json"
	HTTP_RESPONSE_RAISE_FOR_STATUS_METHOD_NAME       = "raise_for_status"
	HTTP_RESPONSE_JSON_ARG_COUNT_ERROR               = "json() takes no arguments (%d given)"
	HTTP_RESPONSE_JSON_ON_RESPONSE_ERROR             = "json() must be called on an HTTPResponse object"
	HTTP_RESPONSE_RAISE_FOR_STATUS_ARG_COUNT_ERROR   = "raise_for_status() takes no arguments (%d given)"
	HTTP_RESPONSE_RAISE_FOR_STATUS_ON_RESPONSE_ERROR = "raise_for_status() must be called on an HTTPResponse object"
	HTTPClientErrorFormat                            = "%d %s for url: %s"
	HTTPServerErrorFormat                            = "%d %s for url: %s"
	HTTP_JSON_MAX_RECURSION_DEPTH                    = "max recursion depth for JSON conversion"

	HTTP_RESPONSE_STATUS_CODE_ATTR       = "status_code"
	HTTP_RESPONSE_TEXT_ATTR              = "text"
	HTTP_RESPONSE_CONTENT_ATTR           = "content"
	HTTP_RESPONSE_HEADERS_ATTR           = "headers"
	HTTP_RESPONSE_URL_ATTR               = "url"
	HTTP_RESPONSE_ENCODING_ATTR          = "encoding"
	HTTP_RESPONSE_REASON_ATTR            = "reason"
	HTTP_REQUEST_METHOD_ATTR             = "method"
	HTTP_REQUEST_URL_ATTR                = "url"
	HTTP_REQUEST_HEADERS_ATTR            = "headers"
	HTTP_REQUEST_BODY_ATTR               = "body"
	HTTPResponseJsonMethodName           = "HTTPResponse.json"
	HTTPResponseRaiseForStatusMethodName = "raise_for_status"

	HTTP_TrueString        = "true"
	HTTP_FalseString       = "false"
	HTTP_NoneString        = "null"
	HTTP_ContentTypeHeader = "Content-Type"
	HTTP_AcceptHeader      = "Accept"
	HTTP_UTF8Encoding      = "utf-8"
	HTTP_JSONContentType   = "application/json"
	HTTP_CharsetEquals     = "charset="
)

// Helper (from object/helpers.go)
const (
	HELPER_NO_TOKEN_LITERAL                                = "internal"
	HELPER_TRUTHY_PROPAGATED_ERROR                         = "(propagated from IsTruthy): %v"
	HELPER_TRUTHY_INTERNAL_ERROR_UNKNOWN_TYPE              = "InternalError: __bool__ returned error object of unknown type %T"
	HELPER_TRUTHY_BOOL_RETURN_TYPE_ERROR                   = "__bool__ should return bool, returned %s"
	HELPER_TRUTHY_LEN_SHOULD_RETURN_NON_NEGATIVE           = "__len__() should return >= 0"
	HELPER_TRUTHY_LEN_RETURN_TYPE_ERROR                    = "__len__() should return an integer, not %s"
	HELPER_TRUTHY_INTERNAL_ERROR_UNKNOWN_LEN_TYPE          = "InternalError: __len__ returned error object of unknown type %T"
	HELPER_APPLY_BOUND_METHOD_ARITY_ERROR                  = "%s.%s() takes %d positional arguments but %d were given"
	HELPER_APPLY_BOUND_METHOD_CLASS_PLACEHOLDER            = "<Class>"
	HELPER_APPLY_BOUND_METHOD_INSTANCE_NIL_CLASS           = "<InstanceWithNilClass>"
	HELPER_IS_INSTANCE_ARG2_TYPE_ERROR                     = "isinstance() arg 2 must be a type or tuple of types, not %s"
	HELPER_IS_INSTANCE_INTERNAL_NIL_CLASS                  = "object.Instance has nil Class"
	HELPER_IS_INSTANCE_INTERNAL_NIL_ERROR_CLASS            = "Pylearn Error object has no ErrorClass"
	HELPER_IS_INSTANCE_INTERNAL_NIL_STOP_ITERATION_CLASS   = "Pylearn StopIterationError object has no ErrorClass"
	HELPER_IS_INSTANCE_MRO_NIL_ERROR                       = "Cannot perform isinstance check: object's class or MRO is nil"
	HELPER_IS_SUBCLASS_NOT_IMPLEMENTED                     = "issubclass check"
	HELPER_COMPARE_OBJECTS_UNSUPPORTED_OP                  = "CompareObjects called with unsupported operator '%s'"
	HELPER_COMPARE_OBJECTS_ATTR_NOT_CALLABLE               = "%s attribute not callable"
	HELPER_COMPARE_OBJECTS_DUNDER_NON_BOOL_RETURN          = "'%s' returned non-Boolean (type %s)"
	HELPER_COMPARE_OBJECTS_EQ_NON_BOOL_FALLBACK            = "'==' comparison did not return Boolean in '!=' fallback"
	HELPER_COMPARE_OBJECTS_NUMERIC_FALLBACK_UNSUPPORTED_OP = "fallback numeric comparison for operator '%s' not supported"
	HELPER_COMPARE_OBJECTS_STRING_FALLBACK_UNSUPPORTED_OP  = "fallback string comparison for operator '%s' not supported"
	HELPER_COMPARE_OBJECTS_BOOL_UNSUPPORTED_OP             = "'%s' not supported between instances of 'bool' and 'bool'"
	HELPER_COMPARE_OBJECTS_BOOL_FALLBACK_UNSUPPORTED_OP    = "fallback boolean comparison for operator '%s' not supported"
	HELPER_COMPARE_OBJECTS_NONE_UNSUPPORTED_OP             = "'%s' not supported between instances of '%s' and '%s'"
	HELPER_COMPARE_OBJECTS_NONE_FALLBACK_UNSUPPORTED_OP    = "fallback None comparison for operator '%s' not supported"
	HELPER_COMPARE_OBJECTS_GENERAL_TYPE_ERROR              = "'%s' not supported between instances of '%s' and '%s'"
	HELPER_CALL_GET_ATTR_TYPE_ERROR                        = "'%s' object has no attributes (cannot get '%s')"
	HELPER_NEW_ERROR_UNKNOWN_CLASS_WARNING                 = "Warning: Unknown error class '%s' used in NewError. Falling back to Exception.\n"
	HELPER_NEW_ERROR_CRITICAL_EXCEPTION_NOT_FOUND          = "Critical: Base 'Exception' class not found for error: %s"
	HELPER_NEW_ERROR_UNEXPECTED_STOP_ITERATION             = "unexpected StopIteration during import: %v"
	HELPER_NEW_DICT_KEY_HASH_ERROR                         = "failed to hash key: %v"
)

// Function object (from object/function_object.go)
const (
	FUNCTION_INSPECT_METHOD_NAME           = "<method>"
	FUNCTION_INSPECT_FUNCTION_BODY         = "{ [function body] }"
	FUNCTION_INSPECT_LAMBDA_NAME           = "<lambda>"
	FUNCTION_INSPECT_PARAM_ASSIGN_OP       = "="
	FUNCTION_INSPECT_PARAMS_SEPARATOR      = ", "
	FUNCTION_INSPECT_VAR_ARG_PREFIX        = "*"
	FUNCTION_INSPECT_KW_ARG_PREFIX         = "**"
	FUNCTION_INSPECT_DEF_KEYWORD           = "def "
	FUNCTION_INSPECT_PAREN_OPEN            = "("
	FUNCTION_INSPECT_PAREN_CLOSE_WITH_BODY = ") { [function body] }"
	FUNCTION_HASH_UNHASHABLE_ERROR         = "unhashable type: %s"
	FUNCTION_GET_ATTR_NAME_ATTR            = "__name__"
	BUILTIN_INSPECT_FORMAT                 = "<built-in function %s>"
	ASYNC_RESULT_PENDING                   = "pending"
	ASYNC_RESULT_FAILED_FORMAT             = "failed: %v"
	ASYNC_RESULT_COMPLETED                 = "completed"
	ASYNC_RESULT_INSPECT_FORMAT            = "<AsyncResult %s>"
)

// File object (from object/file_object.go)
const (
	FILE_OBJECT_CLOSED_STATUS                  = " (closed)"
	FILE_OBJECT_FD_UNKNOWN_FORMAT              = "fd=?"
	FILE_OBJECT_INSPECT_FORMAT                 = "<_io.TextIOWrapper name=%q mode=%q%s>"
	FILE_OBJECT_READ_ON_FILE_ERROR             = "read() must be called on a File object"
	FILE_OBJECT_READ_CLOSED_ERROR              = "I/O operation on closed file"
	FILE_OBJECT_READ_SIZE_TYPE_ERROR           = "read() size argument must be an integer or None"
	FILE_OBJECT_READ_BINARY_ERROR_MSG          = "Error reading binary file: %v"
	FILE_OBJECT_READ_TEXT_ERROR_MSG            = "Error reading text file: %v"
	FILE_OBJECT_READLINE_ON_FILE_ERROR         = "readline() must be called on a File object"
	FILE_OBJECT_READLINE_SIZE_NOT_IMPL         = "readline() with size argument not yet implemented"
	FILE_OBJECT_READLINE_BINARY_ERROR_MSG      = "Error during binary readline: %v"
	FILE_OBJECT_READLINE_TEXT_ERROR_MSG        = "Error during text readline: %v"
	FILE_OBJECT_READLINES_ON_FILE_ERROR        = "readlines() must be called on a File object"
	FILE_OBJECT_READLINES_HINT_NOT_IMPL        = "readlines() with hint argument not yet implemented"
	FILE_OBJECT_READLINES_BINARY_READ_ERROR    = "readlines binary read error: %v"
	FILE_OBJECT_READLINES_TEXT_READ_ERROR      = "readlines text read error: %v"
	FILE_OBJECT_READLINES_SCANNER_ERROR_MSG    = "Error scanning file for readlines: %v"
	FILE_OBJECT_WRITE_ON_FILE_ERROR            = "write() must be called on a File object"
	FILE_OBJECT_WRITE_CLOSED_ERROR             = "I/O operation on closed file"
	FILE_OBJECT_WRITE_BINARY_TYPE_ERROR        = "write() argument must be bytes when file is opened in binary mode, not str"
	FILE_OBJECT_WRITE_TEXT_TYPE_ERROR          = "write() argument must be str when file is opened in text mode, not bytes"
	FILE_OBJECT_WRITE_ARG_TYPE_ERROR           = "write() argument must be str or bytes, not %s"
	FILE_OBJECT_WRITE_ERROR_MESSAGE            = "Error writing to file: %v"
	FILE_OBJECT_CLOSE_ON_FILE_ERROR            = "close() must be called on a File object"
	FILE_OBJECT_CLOSE_ERROR_MESSAGE            = "Error closing file: %v"
	FILE_OBJECT_ENTER_ON_FILE_ERROR            = "__enter__() must be called on a File object"
	FILE_OBJECT_EXIT_ON_FILE_ERROR             = "__exit__() must be called on a File object"
	FILE_OBJECT_ITER_TEXT_READER_NOT_INIT      = "file Reader not initialized for text iteration"
	FILE_OBJECT_ITER_ERROR_MESSAGE             = "Error during file iteration: %v"
	FILE_OBJECT_READER_NOT_INIT_ERROR          = "file Reader not initialized for text mode"
	FILE_OBJECT_READLINES_TEXT_READER_NOT_INIT = "file Reader not initialized for readlines"
	FILE_OBJECT_WRITE_ARG_COUNT_ERROR          = "write() takes exactly one argument (%d given)"
	FILE_OBJECT_CLOSE_ARG_COUNT_ERROR          = "close() takes no arguments (%d given)"
	FILE_OBJECT_CLOSING_ERROR                  = "Error closing file: %v"
	FILE_OBJECT_ENTER_ARG_COUNT_ERROR          = "__enter__() takes no arguments (excluding self)"
	FILE_OBJECT_EXIT_ARG_COUNT_ERROR           = "__exit__() takes 3 arguments (excluding self)"
	// FILE_OBJECT_ITER_BINARY_NOT_IMPL           = "Iterating line-by-line over binary files not fully implemented via Next()"

	FileMethodPrefix          = "File."
	FileReadMethodName        = "read"
	FileReadLineMethodName    = "readline"
	FileReadLinesMethodName   = "readlines"
	FileWriteMethodName       = "write"
	FileCloseMethodName       = "close"
	FileClosedAttributeName   = "closed"
	FileNameAttributeName     = "name"
	FileModeAttributeName     = "mode"
	FileFdAttributeName       = "fd"
	FileEnterDunderMethodName = "__enter__"
	FileExitDunderMethodName  = "__exit__"
	FileInspectMethodName     = "__str__"
)

// Exceptions (from object/exceptions.go)
const (
	EXCEPTION_MRO_COMPUTATION_FAILED                      = "FATAL: Could not compute MRO for built-in exception '%s': %v"
	ERROR_OBJECT_NO_CLASS                                 = "Pylearn Error object has no ErrorClass"
	EXCEPTION_INIT_MSG_PARAM_NAME                         = "msg"
	INIT_REQUIRES_SELF_ARGUMENT                           = "__init__ requires a 'self' argument"
	INIT_MUST_CALL_ON_AN_EXCEPTION_INSTANCE_NOT_OTHER     = "__init__ must be called on an Exception instance, not %s"
	STR_TAKES_EXACTLY_ONE_ARGUMENT__SELF                  = "__str__ takes exactly one argument (self)"
	STR_MUST_BE_CALLED_ON_AN_EXCEPTION_INSTANCE_NOT_OTHER = "__str__ must be called on an Exception instance, not %s"
)

const (
	// Object Types (from object/object.go)
	SUPER_OBJECT_INSPECT_UNKNOWN_TYPE = "UnknownType"
	SUPER_OBJECT_INSPECT_UNKNOWN_SELF = "UnknownSelf"
	SUPER_OBJECT_INSPECT_FORMAT       = "<super: <class '%s'>, <%s object>>"

	// Class object (from object/class_object.go)
	CLASS_OBJECT_DUNDER_NAME_ATTR = "__name__"
)

// Dictionary object (from object/dictionary_object.go)
const (
	DICT_INSPECT_OPEN_BRACE              = "{"
	DICT_INSPECT_PAIR_SEPARATOR          = ": "
	DICT_INSPECT_SEPARATOR               = ", "
	DICT_INSPECT_CLOSE_BRACE             = "}"
	DICT_GET_ARG_COUNT_ERROR             = "get() takes 1 or 2 arguments but %d were given"
	DICT_GET_ON_DICT_ERROR               = "get() must be called on a Dict object"
	DICT_KEYS_ON_DICT_ERROR              = "keys() takes no arguments but %d were given (excluding self)"
	DICT_METHOD_KEYS_ON_DICT_ERROR       = "keys() must be called on a Dict object"
	DICT_VALUES_ON_DICT_ERROR            = "values() takes no arguments but %d were given (excluding self)"
	DICT_METHOD_VALUES_ON_DICT_ERROR     = "values() must be called on a Dict object"
	DICT_ITEMS_ON_DICT_ERROR             = "items() takes no arguments but %d were given (excluding self)"
	DICT_METHOD_ITEMS_ON_DICT_ERROR      = "items() must be called on a Dict object"
	DICT_UPDATE_ARG_COUNT_ERROR          = "update() takes 1 argument but %d were given (excluding self)"
	DICT_UPDATE_ON_DICT_ERROR            = "update() must be called on a Dict object"
	DICT_UPDATE_ARG_TYPE_ERROR           = "update() argument must be a dict (or iterable of pairs - not yet supported), got %s"
	DICT_LEN_ON_DICT_ERROR               = "__len__() must be called on a Dict object"
	DICT_CONTAINS_ARG_COUNT_ERROR        = "__contains__() takes 1 argument (excluding self)"
	DICT_CONTAINS_ON_DICT_ERROR          = "__contains__() must be called on a Dict object"
	DICT_INSPECT_PAIR_SEPARATOR_FORMAT   = "%s: %s"
	DICT_UNHASHABLE_TYPE_ERROR_FORMAT    = "unhashable type: '%s'"
	DICT_FAILED_TO_HASH_KEY_ERROR_FORMAT = "failed to hash key: %v"
	DICT_KEY_ERROR_FORMAT                = "%s"

	DictMethodPrefix       = "Dict."
	DictGetMethodName      = "get"
	DictKeysMethodName     = "keys"
	DictValuesMethodName   = "values"
	DictItemsMethodName    = "items"
	DictUpdateMethodName   = "update"
	DictLenMethodName      = "__len__"
	DictContainsMethodName = "__contains__"
	DictInspectMethodName  = "__str__"
)

// Enumerate object (from object/enumerate_object.go)
const (
	ENUMERATE_ITERATOR_OBJ_TYPE         = "ENUMERATE_ITERATOR"
	ENUMERATE_ITERATOR_UNKNOWN_ITERABLE = "unknown_iterable"
	ENUMERATE_ITERATOR_INSPECT_FORMAT   = "<enumerate_iterator for %s at %p, current_index=%d>"
)

// Enumerate object (from object/enumerate_object.go)
const (
	OBJECT_TYPE_REGEX_PATTERN  = "REGEX_PATTERN"
	OBJECT_TYPE_REGEX_MATCH    = "REGEX_MATCH"
	OBJECT_TYPE_REGEX_ITERATOR = "REGEX_ITERATOR"
)
