//go:build sw
package constants

// pylearn/internal/parser/parser.go
const (
	ParserExpectedDefOrClassAfterDecorator     = "expected 'def' or 'class' after decorator(s)"
	ParserExpectedDefAfterAsync                = "expected 'def' after 'async', got %s"
	ParserExpectedExpressionAfterWith          = "line %d:%d: expected expression after 'with'"
	ParserIdentifierAfterAs                    = "identifier after 'as' in 'with' statement"
	ParserIndentedBlockForWithStatement        = "indented block for 'with' statement body"
	ParserExpectedIndentedBlockTry             = "line %d:%d: expected indented block after 'try:'"
	ParserExpectedExceptOrFinally              = "line %d:%d: expected 'except' or 'finally' block after 'try' body"
	ParserBareExceptCannotUseAs                = "line %d:%d: bare except clause cannot use 'as'"
	ParserIdentifierAfterAsExcept              = "identifier after 'as' in except clause" // "identifier for alias after 'as'"
	ParserExpectedIndentedBlockExcept          = "line %d:%d: expected indented block after 'except' clause"
	ParserExpectedModuleNameImport             = "line %d:%d: expected module name (identifier) after 'import'"
	ParserExpectedParenStarOrIdentImport       = "'(', '*' or identifier after 'import'"
	ParserExpectedIdentToImport                = "identifier to import"
	ParserExpectedClosingParenImportList       = "closing ')' for import list"
	ParserExpectedCommaOrCloseParenImport      = "expected ',' or ')' after import item, got %s'" //"',' or ')' after identifier in list, got %s"
	ParserExpectedClassnameClass               = "line %d:%d: expected class name (identifier) after 'class'" 
	ParserExpectedCloseParenSuperclassList     = "line %d:%d: expected ')' after superclass list, got %s"
	ParserExpectedIndentedBlockOrPassClass     = "line %d:%d: expected an indented block or 'pass' for class body after ':'"
	ParserExpectedIdentifierAfterDot           = "line %d:%d: expected identifier after '.'"
	ParserInternalErrorMalformedIndentLbrace   = "line %d:%d: internal parser error or malformed indent for LBRACE"
	ParserExpectedClosingBraceDictDedent       = "line %d:%d: expected '}' after dedent for empty indented literal, got %s"
	ParserUnterminatedIndentedDictLiteral      = "line %d:%d: unterminated indented dictionary literal (EOF)"
	ParserUnexpectedBraceIndentedDict          = "line %d:%d: unexpected '}' after comma in indented dict, expected new key or DEDENT"
	ParserExpectedClosingBraceDict             = "expected '}' after dictionary, got %s"
	ParserExpectedClosingBraceSetDedent        = "line %d:%d: expected '}' after set dedent, got %s"
	ParserUnterminatedIndentedSetLiteral       = "line %d:%d: unterminated indented set literal (EOF)"
	ParserUnexpectedBraceIndentedSet           = "line %d:%d: unexpected '}' after comma in indented set, expected new element or DEDENT"
	ParserUnexpectedEOFExpression              = "line %d:%d: unexpected EOF while parsing expression"
	ParserNoPrefixParseFn                      = "line %d:%d: no prefix parse function for %s found"
	ParserNonDefaultArgFollowsDefault          = "line %d:%d: non-default argument '%s' follows default argument"
	ParserIdentAsteriskDoubleAsteriskParam     = "identifier, '*', or '**' in parameter list"
	ParserCommaOrCloseParenAfterParam          = "',' or ')' after parameter"
	ParserCloseParenParamList                  = "')' to close parameter list"
	ParserExpectedIndentedBlockFunctionBody    = "indented block for function body"
	ParserExpectedExpressionAfterStar          = "line %d:%d: expected %s argument after %s"
	ParserExpectedExpressionAfterDoubleStar    = "expression after '**'"
	ParserExpectedExpressionAfterSingleStar    = "expression after '*'"
	ParserValueAfterKwargAssignment            = "value after keyword argument assignment"
	ParserUnexpectedTokenInArgList             = "line %d:%d: unexpected '%s' at start of argument list or after comma"
	ParserExpectedArgOrCloseParen              = "argument or ')'"
	ParserCommaOrCloseParenAfterArg            = "',' or ')' after function argument"
	ParserCloseParenArgList                    = "')' to close argument list"
	AfterLoopText                              = " (after loop)"
	ParserInternalErrorSingleLineTuple         = "line %d:%d: internal parser error: expected comma or ')' in single-line tuple, got %s"
	ParserUnexpectedCommaTuple                 = "line %d:%d: unexpected comma, expected element in indented tuple"
	ParserUnexpectedCloseParenIndentedTuple    = "line %d:%d: unexpected ')' in indented tuple before DEDENT"
	ParserUnexpectedCommaIndentedTuple         = "line %d:%d: unexpected ')' after comma in indented tuple, expected new element or DEDENT"
	ParserExpectedCommaOrCloseParenTuple       = "line %d:%d: expected comma or ')' after tuple element, got %s"
	ParserListComprehensionFor                 = "'for' in list comprehension"
	ParserListComprehensionLoopVar             = "identifier after '*' for var-positional parameter"
	ParserListComprehensionIn                  = "'in' keyword"
	ParserExpectedClosingBracketListComp       = "expected ']' after list comprehension"
	ParserInternalErrorMalformedIndentList     = "line %d:%d: internal parser error or malformed indent for LBRACKET"
	ParserExpectedClosingBracketListDedent     = "line %d:%d: expected ']' after dedent for empty indented list, got %s"
	ParserUnterminatedIndentedListLiteral      = "line %d:%d: unterminated indented list literal (EOF)"
	ParserUnexpectedBracketIndentedList        = "line %d:%d: unexpected ']' in indented list before DEDENT"
	ParserUnexpectedBracketAfterCommaList      = "line %d:%d: unexpected ']' after comma in indented list, expected new element or DEDENT"
	ParserOnlyOneKwargsParamAllowed            = "line %d:%d: only one **kwargs parameter allowed"
	ParserOnlyOneArgsParamAllowed              = "line %d:%d: only one *args parameter allowed"
	ParserArgsCannotAppearAfterKwargs          = "line %d:%d: *args cannot appear after **kwargs"
	ParserRegularParamCannotAppearAfterStarred = "line %d:%d: regular parameter '%s' cannot appear after *args or **kwargs"
	ParserUnexpectedEOF                        = "line %d:%d: unexpected EOF"
	ParserExpectedGotInstead                   = "line %d:%d: expected %s, got %s instead"
	ParserExpectedGot                          = "line %d:%d: expected %s, got %s"
	ParserExpectedNextGotInstead               = "line %d:%d: expected next token to be %s, got %s instead"
	ParserExpectedIdentInList                  = "line %d:%d: expected identifier in list, got %s"
	ParserExpectedCommaOrCloseParenIdList      = "line %d:%d: expected ',' or '%s' after identifier in list, got %s"
	ParserExpectedCloseDelimiterIdList         = "line %d:%d: expected '%s' to close identifier list, got %s"
	ParserExpectedIndentedBlockIfCondition     = "line %d:%d: expected indented block after 'if' condition"
	ParserExpectedIndentedBlockElifCondition   = "line %d:%d: expected indented block after 'elif' condition"
	ParserInternalErrorExpectedElse            = "Internal parser error: expected ELSE, got %s"
	ParserExpectedIndentedBlockElse            = "line %d:%d: expected indented block after 'else:' (got %s)"
	ParserExpectedIndentedBlockWhileCondition  = "line %d:%d: expected indented block after 'while' condition"
	ParserExpectedIndentedBlockForStatement    = "line %d:%d: expected indented block after 'for' statement"
	ParserCouldNotParseAsInteger               = "line %d:%d: could not parse %q as integer: %s"
	ParserCouldNotParseAsFloat                 = "line %d:%d: could not parse %q as float: %s"
	ParserOpenParenParam                       = "'(' to start parameter list"
	ParserInvalidAssignmentTarget              = "line %d:%d: invalid assignment target: cannot assign to %s"
	ParserInvalidBytesLiteral                  = "line %d:%d: invalid bytes literal: %v"
	ParserInvalidBytesLiteralFormat            = "invalid bytes literal format: %q"
	ParserUnterminatedBytesLiteral             = "unterminated bytes literal (ends with '\\')"
	ParserInvalidOctalEscape                   = "invalid octal escape: \\%s"
	ParserInvalidHexEscapeTooShort             = "invalid hex escape sequence \\x (too short)"
	ParserInvalidHexEscape                     = "invalid hex escape sequence: \\x%s"
	ParserUnicodeEscapeNotAllowed              = "unicode escape sequences are not allowed in bytes literals: \\%c"
	ParserUnescapedQuoteInBytesLiteral         = "unescaped quote character inside bytes literal content"
	ParserExpectedCloseParenTupleDedent        = "line %d:%d: expected ')' after tuple dedent, got %s"
	ParserUnterminatedIndentedTupleLiteral     = "line %d:%d: unterminated indented tuple literal (EOF)"

	IterableKeyword = "iterable"
	MappingKeyword  = "mapping"
)


const (
	// New constants for bytes literal parsing
	ParserBytesASCIIOnlyError          = "invalid bytes literal: bytes can only contain ASCII literal characters"
	ParserTrailingBackslashError       = "invalid bytes literal: trailing backslash"
	ParserHexNeedsTwoDigitsError       = "invalid bytes literal: \\x escape needs two hex digits"
	ParserUnterminatedTripleQuoteError = "invalid bytes literal: unterminated triple-quoted string in %q"
	ParserUnterminatedQuoteError       = "invalid bytes literal: unterminated string in %q"
	ParserMissingBPrefixError          = "invalid bytes literal format: missing 'b' prefix in %q"
)


// Parser error messages for imports
const (
	// ParserExpectedClosingParenImportList = "expected closing ')' in import list, got %s"
	// ParserExpectedParenStarOrIdentImport = "expected '(', '*', or identifier after 'import'"
	ParserExpectedDotInModulePath        = "expected '.' in module path, got %s"
	ParserExpectedIdentAfterDot          = "expected identifier after '.', got %s"
	ParserExpectedIdentInImportList      = "expected identifier in import list, got %s"
	// ParserExpectedIdentifierAfterDot     = "line %d:%d: expected identifier after '.'"
)